#!/usr/bin/env node
/**
 * scripts/inject-env.js
 * ─────────────────────────────────────────────────────────────
 * Reads scripts/.resolved-ports.json (written by find-ports.js)
 * and regenerates:
 *
 *   apps/frontend/.env.<portal>   — for each Vite portal
 *   scripts/.allowed-origins.txt  — comma-separated origins for backend CORS
 *
 * Called automatically by start_all.sh AFTER find-ports.js.
 * Safe to re-run — all files are fully overwritten.
 */

'use strict'
const fs   = require('fs')
const path = require('path')

const PORTALS      = require('./portals.config.js')
const RESOLVED_OUT = path.join(__dirname, '.resolved-ports.json')
const FRONTEND_DIR = path.join(__dirname, '..', 'apps', 'frontend')
const ORIGINS_OUT  = path.join(__dirname, '.allowed-origins.txt')

if (!fs.existsSync(RESOLVED_OUT)) {
  console.error('[inject-env] ERROR: .resolved-ports.json not found. Run find-ports.js first.')
  process.exit(1)
}

const resolved = JSON.parse(fs.readFileSync(RESOLVED_OUT, 'utf8'))

// Build a lookup: portalId → resolved URL
function url(id) {
  const port = resolved[id]
  return port ? `http://localhost:${port}` : ''
}

// ── Write frontend .env files ─────────────────────────────────────────────────
const frontendPortals = PORTALS.filter(p => p.config) // skip backend

for (const portal of frontendPortals) {
  const port      = resolved[portal.id]
  const envFile   = path.join(FRONTEND_DIR, `.env.${portal.mode || portal.id}`)
  const backendUrl = url('backend')

  const lines = [
    `# ${portal.label} — Auto-generated by scripts/inject-env.js`,
    `# DO NOT EDIT MANUALLY — regenerated on every start_all.sh run`,
    ``,
    `VITE_PORTAL_ID=${portal.id}`,
    `VITE_PORTAL_LABEL=${portal.label}`,
    `VITE_DEV_PORT=${port}`,
    `VITE_API_BASE_URL=${backendUrl}/api`,
    `VITE_API_ORIGIN=${backendUrl}`,
    ``,
    `# Cross-portal redirect URLs`,
    `VITE_PORTAL_URL_LANDING=${url('landing')}`,
    `VITE_PORTAL_URL_FACULTY=${url('faculty')}`,
    `VITE_PORTAL_URL_HIRING=${url('hiring')}`,
    `VITE_PORTAL_URL_CHRO=${url('chro')}`,
    `VITE_PORTAL_URL_RECRUITER=${url('recruiter')}`,
    `VITE_PORTAL_URL_CANDIDATE=${url('candidate')}`,
  ]

  fs.writeFileSync(envFile, lines.join('\n') + '\n')
  console.log(`[inject-env] Wrote ${path.relative(process.cwd(), envFile)}  (port ${port})`)
}

// Also update the base .env for landing (uses default vite.config.js, mode=null)
const landingPort = resolved['landing']
const backendUrl  = url('backend')
const baseEnvFile = path.join(FRONTEND_DIR, '.env')
const baseLines   = [
  `# Landing Page — Auto-generated by scripts/inject-env.js`,
  `VITE_API_BASE_URL=/api`,
  `VITE_API_ORIGIN=${backendUrl}`,
  `VITE_ASSET_BASE_URL=`,
  `VITE_DEV_PORT=${landingPort}`,
]
fs.writeFileSync(baseEnvFile, baseLines.join('\n') + '\n')
console.log(`[inject-env] Wrote apps/frontend/.env  (port ${landingPort})`)

// ── Write allowed origins for backend CORS ───────────────────────────────────
const origins = frontendPortals.map(p => `http://localhost:${resolved[p.id]}`).filter(Boolean)
fs.writeFileSync(ORIGINS_OUT, origins.join(','))
console.log(`[inject-env] Wrote scripts/.allowed-origins.txt`)
console.log(`[inject-env]   Origins: ${origins.join(', ')}`)
